### ISSUE TITLE
Add a browser list or a target to the babelrc config with preset-env

### ISSUE THREAD

**Issue by chuck-durst** [studiometa/gulp-config#6]
Adding one of these parameters will reduce the number of polyfills and plugins used by babel. There is probably some browsers or browsers versions that we may not wan't to support anymore. 

You can find some best practices and a full list of all the available queries [here](https://github.com/browserslist/browserslist#best-practices). It is also possible to enable a [debug mode](https://babeljs.io/docs/en/babel-preset-env#debug) to see all the plugins and polyfills used for a given browserlist.

**Comment by titouanmathis** [comment]
Babel is currently used only to compile the package scripts, we do not have yet an ES6 options to the scripts' tasks. 

But we will need to keep this in mind when working on #7  🙂
